### ISSUE TITLE
Two of the quotes when adding a new task are backticks/graves, not quotes.

### ISSUE THREAD

**Issue by JustAnotherStrange** [g-w1/work#1]
[Screenshot](https://i.imgur.com/bLqadzf.png)
it says:
`added event with summary ``test" to database`

**Comment by g-w1** [comment]
This is intentional. since there is no way to have quotes facing a direction in the terminal, a lot of projects use this.

**Comment by g-w1** [comment]
In the future I will add a config feature for stuff like this (probably later this week)

**Comment by g-w1** [comment]
Resolved. Config file support added.
