### ISSUE TITLE
failed to run custom build command for `libudev-sys v0.1.4`

### ISSUE THREAD

**Issue by dav** [g-w1/work#2]
Just FYI, got this error trying to run this code:

```
error: failed to run custom build command for `libudev-sys v0.1.4`

Caused by:
  process didn't exit successfully: `/home/dav/code/rust_game/target/debug/build/libudev-sys-8fbb43f5dd300b68/build-script-build` (exit code: 101)
  --- stderr
  thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "`\"pkg-config\" \"--libs\" \"--cflags\" \"libudev\"` did not exit successfully: exit code: 1\n--- stderr\nPackage libudev was not found in the pkg-config search path.\nPerhaps you should add the directory containing `libudev.pc\'\nto the PKG_CONFIG_PATH environment variable\nNo package \'libudev\' found\n"', /home/dav/.cargo/registry/src/github.com-1ecc6299db9ec823/libudev-sys-0.1.4/build.rs:38:41
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
I'm not a rust dev so not going to spend any time to try and figure this out, was just curious to look at the game, but figured I'd let you know in case its something fixable on your side. I just installed rust moments before to try out your `work` app (which seems to be working fine btw, looking forward to giving it a go).

**Comment by g-w1** [comment]
Hi. I think that this is an error with a rust crate ```libudev-sys```. This seems to be a compile time error. I do not think libudev-sys is a dependency of my project 
```bash
~/code/rust/work $ cargo tree | grep udev
~/code/rust/work $
```
To me, it seems like you do not have libudev that the rust crate libudev-sys is binding to. What distro do you use, and what command in the shell did you run to get that error.

It seems like another one of my projects, my platformer game requires libudev-sys, so maybe that is what is going on. You may need to install systemd libraries. (On my distro libudev.so is in systemd libraries.) But the game isn't very good anyways, it was just a test so no need to try it. :) 

Thanks

**Comment by dav** [comment]
That makes sense. Thanks. Yeah I'm not going down this rabbit hole ;)

I'm on Pop!_OS 20.04 LTS
```
uname -a                                                                                                                                                                                                                                                                                               (base)  Mon 05 Oct 2020 07:40:59 AM PDT
Linux dav-laptop 5.4.0-7642-generic #46~1598628707~20.04~040157c-Ubuntu SMP Fri Aug 28 18:02:16 UTC  x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by g-w1** [comment]
Ok. Well since this is not an issue in work, ill close this. It seems like you need to ``sudo apt install libudev-dev`` and ``sudo apt install pkg-config``, but ill leave that up to you if you want. https://stackoverflow.com/questions/55945023/libudev-development-package-not-found.
Thanks

**Comment by IannBridges** [comment]
Thank you @g-w1, your answer allowed me to fix an issue with a completely unrelated project (Rust for avr devices). Cheers.

**Comment by allchain** [comment]
Thanks @g-w1, it works

**Comment by rcolomina** [comment]
Installing `sudo apt install libudev-dev` worked for me.

**Comment by burtonrodman** [comment]
for Ubuntu 22.04.1 LTS in WSL, I needed both:
```
sudo apt install libudev-dev
sudo apt install pkg-config
```
